### ISSUE TITLE
Support for minikube v1.24

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/k8s#126]
https://github.com/kubernetes/minikube/releases/tag/v1.22.0

**Comment by project-administrator** [comment]
1.23 has already been released and 1.24 will be released soon (beta available)
We can use the latest minikube version with the desired kubernetes version (we're using EKS 1.20 now)

**Comment by project-administrator** [comment]
Minikube 1.23.2 works OK for the local sandbox deployment. 
However, it fails the healthchecks and the UI tests when running it in the GH-hosted actions. 
Need to troubleshoot this.

**Comment by project-administrator** [comment]
Newer versions of minikube changed the format of the coredns configMap, and our custom patch fails to apply after the minikube startup. This patch is required for the proper ingress resolution from within the running pods. 
Need to modify the coreDNS configMap patching logic to resolve this issue.

**Comment by project-administrator** [comment]
Added the DNS resolution test to the `coredns_patch.sh` script

**Comment by alialkhalidi** [comment]
https://github.com/trustbloc/sandbox/pull/1270
