### ISSUE TITLE
orb: Update pod probes

### ISSUE THREAD

**Issue by alialkhalidi** [trustbloc/k8s#249]
Currently, orb exposes a simple /healthcheck endpoint to signal container liveness. another endpoint (/.well-known/nodeinfo) reflects completing the startup sequence and "readiness" to serve requests.
adding this will eliminate the false-positves of orb being up but in fact its still not.

**Comment by project-administrator** [comment]
PR: https://github.com/trustbloc/k8s/pull/254

**Comment by project-administrator** [comment]
Roll-back healthcheck URL for init containers: https://github.com/trustbloc/k8s/pull/255
