### ISSUE TITLE
configure credential manifest output descriptors

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/k8s#366]
similar to RP adapter PEx - https://github.com/trustbloc/k8s/blob/main/adapter-rp/kustomize/adapter-rp/overlays/common/rp/config.json

**Comment by sudeshrshetty** [comment]
@rolsonquadras @talwinder50 please confirm if it is done

**Comment by rolsonquadras** [comment]
This has been added in https://github.com/trustbloc/k8s/pull/377/files#diff-53f7db16e9d49f3e63439a491c65e6703478d1e363be8d309724b6f833d774c6R1
